Repository LINE-NOW/LINENOW-Server, pull requests merged in 2024-09, with the labels that each got.

#9 ✨Feature: 사용자 웨이팅 관련 구현 중
  booth/admin.py
  booth/migrations/0001_initial.py
  booth/migrations/0002_alter_event_name.py
  booth/models.py
  booth/serializers.py
  booth/urls.py
  booth/views.py
  linenow/__init__.py
  linenow/celery.py
  linenow/settings.py
  linenow/urls.py
  requirements.txt
  waiting/admin.py
  waiting/migrations/0001_initial.py
  waiting/models.py
  waiting/serializers.py
  waiting/tasks.py
  waiting/urls.py
  waiting/views.py
Labels: ✨Feature, 🐱영신작업

#11 ✨ Feat: 응답 반환 구조 설정
  booth/views.py
  linenow/settings.py
  utils/__init__.py
  utils/exceptions.py
  utils/mixins.py
  utils/responses.py
Labels: ✨Feature, 🐰종범작업

#20 ✨ Feat: Docker-compose.yml 작성
  docker-compose.yml
Labels: ✏️Chore, 🐰종범작업

#19 Create django-deploy.yml
  .github/workflows/django-deploy.yml
Labels: ✏️Chore, 🐰종범작업

#24 💚 Fix: Dockerfile 수정
  Dockerfile
Labels: ✏️Chore, 🐰종범작업

#17 🩹 Fix: 부스 응답 구조 변경
  Dockerfile
  booth/views.py
  utils/exceptions.py
  utils/responses.py
Labels: ✏️Chore, 🐱영신작업

#28 🩹 Fix: 부스 모델 필드 수정, 필요없는 시리얼라이저 필드 제거, 필요없는 API 주석 처리
  booth/migrations/0002_alter_booth_is_operated.py
  booth/migrations/0003_alter_boothmenu_price.py
  booth/models.py
  booth/serializers.py
  booth/views.py
Labels: 🐱영신작업, 🛠️Fix

#8 ✨ Feature/ljb manager
  linenow/settings.py
  linenow/urls.py
  manager/__init__.py
  manager/admin.py
  manager/apps.py
  manager/migrations/0001_initial.py
  manager/migrations/__init__.py
  manager/models.py
  manager/serializers.py
  manager/tests.py
  manager/urls.py
  manager/views.py
Labels: ✨Feature, 🐰종범작업

#41 💚 Fix: django-deploy 수정 pull_request_target 사용
  .github/workflows/django-deploy.yml
Labels: ✏️Chore, 🐰종범작업

#43 💚 Fix: database host 수정
  .github/workflows/django-deploy.yml
Labels: ✏️Chore, 🐰종범작업

#45 💚 Fix: celery.py docker-compose 재연결 활성화
  docker-compose.yml
  linenow/celery.py
Labels: ✏️Chore, 🐰종범작업
