Repository LINE-NOW/LINENOW-Server, pull requests merged in 2024-10, with the labels that each got.

#56 Feature/waiting v2
  waiting/migrations/0002_alter_waiting_waiting_status.py
  waiting/models.py
  waiting/serializers.py
  waiting/tasks.py
  waiting/views.py
Labels: ✨Feature, 🐱영신작업

#58 Feature/waiting v2
  waiting/serializers.py
  waiting/views.py
Labels: 🐱영신작업, 🛠️Fix

#65 ✨ Feature: 관리자 로그인 jwt 구현
  linenow/settings.py
  manager/filters.py
  manager/migrations/0002_admin_user.py
  manager/models.py
  manager/serializers.py
  manager/urls.py
  manager/views.py
  requirements.txt
  utils/CustomCookieAuthentication.py
Labels: ✨Feature, 🐰종범작업

#74 🩹 Fix: settings.py 에 celery 추가
  linenow/settings.py
Labels: ✨Feature, 🐱영신작업

#76 🩹 Fix: 나의 대기 상세에 해당 부스 전체 대기 팀 수 추가 & 3분/10분 더한 필드로 수정
  waiting/serializers.py
Labels: 🐱영신작업, 🛠️Fix

#86 🩹 Fix: 입장 확정 후 10분 지나면 '시간 초과로 인한 대기 취소'로 상태 변경
  waiting/tasks.py
  waiting/views.py
Labels: 🐱영신작업, 🛠️Fix

#87 ⚡ Feature: 관리자 API JWT 인증 로직 수정 및 권한 부여 추가
  accounts/migrations/0001_initial.py
  manager/serializers.py
  manager/views.py
  utils/exceptions.py
  utils/permissions.py
Labels: ✨Feature, 🐰종범작업

#89 🩹 Fix: 일반 유저 권한 추가
  utils/permissions.py
  waiting/views.py
Labels: ✨Feature, 🐱영신작업

#91 ⚡️ Feat: 회원탈퇴 기능 추가
  accounts/urls.py
  accounts/views.py
Labels: ✨Feature, 🐵지윤작업

#98 ✨ Feat: 부스 대기 목록 Ordering fields 구현
  manager/views.py
Labels: ✨Feature, 🐰종범작업

#102 ✨ Feat: [관리자] status별 웨이팅 팀 수 API 추가
  manager/urls.py
  manager/views.py
Labels: ✨Feature, 🐱영신작업

#103 🩹 Fix: is_waiting, waiting_status 반영 잘 되게
  booth/serializers.py
Labels: 🐱영신작업, 🛠️Fix

#104 🩹 Fix: 부스 리스트 & 디테일 - 대기 팀 수, 내 앞에 대기 팀 수, 내 waiting_id 수정 및 추가
  booth/serializers.py
  booth/views.py
Labels: 🐱영신작업, 🛠️Fix

#107 🩹 Fix: 한 웨이팅 '입장 확정' 시 다른 웨이팅 모두 취소
  waiting/views.py
Labels: 🐱영신작업, 🛠️Fix

#108 🩹 Fix: settings.py renderer 추가
  booth/models.py
  linenow/settings.py
Labels: 🐱영신작업, 🛠️Fix

#111 🩹 Fix: 운영 상태에 따른 부스 정렬 추가
  booth/views.py
Labels: ✏️Chore, 🐱영신작업

#112 🩹 Fix: 부스 리스트에서도 status 3개만 포함하게 수정
  booth/views.py
Labels: 🐱영신작업, 🛠️Fix
